### ISSUE TITLE
Maio 1.4.5

### ISSUE THREAD

**Issue by omatty198** [googleads/googleads-mobile-ios-mediation#104]
maio released another version of their SDK fixing a critical bug that crashes the UI.
However `GoogleMobileAdsMediationMaio` version is v1.4.2.
Could we update the mediation to this version too?

https://github.com/imobile-maio/maio-iOS-SDK/releases/tag/v1.4.5
https://github.com/imobile-maio/maio-iOS-SDK/releases/tag/v1.4.4

Thanks!

**Comment by maninomula** [comment]
@omatty198 Currently we are woking on updating the maio adapter to use our [new rewarded API](https://developers.google.com/admob/ios/rewarded-ads). So please bear with us until we update the adapter.

Thanks.

**Comment by maninomula** [comment]
Maio Adapter version 1.4.6.0 which is compatible with Maio SDK 1.4.6 is live.
