### ISSUE TITLE
GoogleMobileAdsMediationUnity crash on iOS

### ISSUE THREAD

**Issue by aplusm** [googleads/googleads-mobile-ios-mediation#106]
Configuration:
- iOS 12.1.4
- Firebase/AdMob (5.18.0)
- Google-Mobile-Ads-SDK (~> 7.40)
- GoogleMobileAdsMediationUnity (3.0.0.3)

My app crashes while requesting ads with Unity at -[GADMAdapterUnityWeakReference initWithObject:] + 4313131528

A complete trace is attached to this issue.

[Crashed: com.apple.main-thread.txt](https://github.com/googleads/googleads-mobile-ios-mediation/files/2969816/Crashed.com.apple.main-thread.txt)

**Comment by maninomula** [comment]
Thanks for bringing the issue in. We have released a new version of the Unity adapter (3.0.1.0) which solves this issue.
