### ISSUE TITLE
googleads-mobile-ios-mediation build failed with error

### ISSUE THREAD

**Issue by fan-c-yu** [googleads/googleads-mobile-ios-mediation#108]
https://github.com/googleads/googleads-mobile-ios-mediation/blob/master/adapters/Nend/NendAdapter/GADMAdapterNend.m#L34

Maybe `gadAdSize` is correct.
```
GADAdSize closestSize = GADClosestValidSizeForAdSizes(gadAdSize, potentials);
```
Thanks!

**Comment by stowy** [comment]
Resolved.
