### ISSUE TITLE
Swift version

### ISSUE THREAD

**Issue by nharbo** [googleads/googleads-mobile-ios-mediation#11]
Hey guys! Can you please do a swift example? :-)
Best, 
Nicolai

**Comment by ericleich** [comment]
Most of the resources in this example are for ad network partners to build adapters, which typically still build in ObjC. Custom events are the only piece that any Google Mobile Ads SDK publisher may write themselves if they need their own custom adapter.

Is custom events the part you want to see Swift support for? Maybe we can update the existing project to have a Swift-based Sample Adapter custom event that interops with the existing ObjC Sample SDK.

**Comment by nharbo** [comment]
Thanks for your reply!
Yes please, I would love a swift-based example of how to use custom events! :-) 
Do you think that would be possible?

**Comment by ericleich** [comment]
@nharbo It is possible, but it isn't work we planned for in Q2. We will plan to add this in Q3. I'll leave the issue open.

**Comment by maninomula** [comment]
Swift based example for custom events has been added.
