### ISSUE TITLE
Crash in [GADMAdapterMoPub loadNativeAdImages]

### ISSUE THREAD

**Issue by popic28** [googleads/googleads-mobile-ios-mediation#13]
We have a 300 crashes per day coming from the mopub adapter framework, and after checking the stacktrace the are coming from `GADMAdapterMoPub`'s `loadNativeAdImages` method. We've found that the crash is caused by inserting a nil object into an array. I'll open a PR with a fix (just a nil check before adding the URL to the images array)

**Comment by ericleich** [comment]
Commentary is in #14 . Basically, we're working with MoPub on getting to the bottom of this; we think the issue may be malformed urls.

**Comment by yood** [comment]
+1.

I'm getting a stream of crashes everyday at `-[GADMAdapterMoPub loadNativeAdImages]` with the error:

>    Fatal Exception: NSInvalidArgumentException
>    *** -[__NSArrayM insertObject:atIndex:]: object cannot be nil

I'm using these pods:
- Firebase/AdMob (4.8.0):
    - Firebase/Core
    - Google-Mobile-Ads-SDK (= 7.27.0)
- GoogleMobileAdsMediationMoPub (4.19.0.0):
    - Google-Mobile-Ads-SDK (>= 7.14.0)
    - mopub-ios-sdk/Core (= 4.19.0)

**Comment by popic28** [comment]
It's 6 months later and still the issue isn't resolved, and the solution 

> Commentary is in #14 . Basically, we're working with MoPub on getting to the bottom of this; we think the issue may be malformed urls.

definitely did not pan out. 
Regardless of the malformed URL's or anything, the issue itself is about using an API that you don't want to use as it's vendor intends, namely the NSURL and NSArray API's. the breakdown goes like this : 
1. [NSURL URLWithString] says that it can return nil 
2. [NSMutableArray addObject:] will crash for object = nil

So when you want to write :
NSURL *URL = [NSURL URLWithString:_nativeAd.properties[key]]; 
[imageURLs addObject:URL];
you have to check that URLWithString did not return nil. 
If you want to 'fail early' you can add an assertion there, and handle the case gracefully in production instead of just crashing because 'the URL was malformed' and especially if what you're shipping is a third party ads framework that tons of live apps rely on. 

I hope the issue gets reopened or fixed soon.

**Comment by bitomule** [comment]
Any update on this? We're still having the same issue.

**Comment by maninomula** [comment]
I think the changes are live. Please take a look and get back to us.

**Comment by bitomule** [comment]
@maninomula do you know what version was it included? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by maninomula** [comment]
It is released in MoPubAdapter version 4.20.0.0.

**Comment by maninomula** [comment]
@bitomule There are new versions of the SDK as-well. Please let us know if they are okay for your use.

**Comment by maninomula** [comment]
Closing this issue as it is inactive for more than 30 days. Please create a new issue if you are facing this problem again. 

Thanks
