### ISSUE TITLE
Cocoa Pods can't read Unity License file

### ISSUE THREAD

**Issue by Izzyjm** [googleads/googleads-mobile-ios-mediation#137]
after installing the Unity mediation adapter I get this in the terminal, what exactly does it mean that it can't find the LICENSE file does this affect anything major or just a warning ?
![Screen Shot 2019-08-01 at 1 56 37 PM](https://user-images.githubusercontent.com/24462583/62319720-39be1a80-b464-11e9-802f-41003cb52d5f.png)

**Comment by maninomula** [comment]
I believe this is just a warning and it comes from the Unity Ads SDK pod. So I think reaching out to unity ads is a better alternative.
