### ISSUE TITLE
Reference variable error

### ISSUE THREAD

**Issue by ghost** [googleads/googleads-mobile-ios-mediation#143]
https://github.com/googleads/googleads-mobile-ios-mediation/blob/57036808089e09889351f1f60c67ec3d0a9e602c/adapters/IronSource/IronSourceAdapter/ISMediationManager.m#L367    should use self.interstitialAdapterDelegates instead of self.rewardedAdapterDelegates

**Comment by maninomula** [comment]
The issue has been resolved and a new version go the adapter is released.
