### ISSUE TITLE
GoogleMobileAdsMediationUnity requires Google-Mobile-Ads-SDK (>= 7.49.0)

### ISSUE THREAD

**Issue by marcelo-fanatee** [googleads/googleads-mobile-ios-mediation#148]
change log says `- Now requires Google Mobile Ads SDK version 7.46.0 or higher.`

but podspec says
```
"dependencies": {
    "UnityAds": "3.2.0",
    "Google-Mobile-Ads-SDK": ">= 7.49.0"
  },
```

**Comment by maninomula** [comment]
Thanks for bringing up the issue. We always encourage the publishers to use the latest version of the GoogleMobileAdsSDK. We will update the ChangeLog soon.

**Comment by maninomula** [comment]
The team has discussed regarding this and decided to use the latest version of the GoogleMobileAds SDK for the pods and the change log will be updated from the next version.
