### ISSUE TITLE
UnityAdapter.framework is empty

### ISSUE THREAD

**Issue by Deathwing** [googleads/googleads-mobile-ios-mediation#16]
Hey!

We are using Unity 5.6.0p3 and used Google Ads for a while now. But it seems that the UnityAdapter 2.1.0.0 is not working with the built .framework.
If using the .framework the following error happens:
<Google> Cannot find an ad network adapter with the name(s): GADMAdapterUnity. Remember to link all required ad network adapters and SDKs, and set -ObjC in the 'Other Linker Flags' setting of your build target.

So later ad retrieving (when only using Unity ads as adapter, same for interstitial of course):
AdMob::OnAdFailedToLoad: GoogleMobileAds.Api.RewardBasedVideoAd with Failed to receive ad with error: No ad returned from any ad server.

I have looked into the .framework and it seems it is completely empty, so i decided to download the repo and built it. Same issue. I mean the built framework is only 29bytes large.
I could fix this issue for me with building the Library instead of the Framework.

Unluckily my Xcode skills are super rusted, I will not try to fix the framework issue on my own :)

If you need further information from me, feel free to ask.

Cheers

**Comment by maninomula** [comment]
There is new version of UnityAdapter 2.2.1.0. Please use this framework and get back to us if you have any issues. 
Thanks

**Comment by maninomula** [comment]
Closing this issue as it is inactive for more than 30 days.
