### ISSUE TITLE
Update MoPub adapter to support MoPub SDK 5.10.0

### ISSUE THREAD

**Issue by charliefancelli** [googleads/googleads-mobile-ios-mediation#168]
Is there a plan to update the MoPub adapter to support the current release of the MoPub SDK 5.10.0? 
The currently supported MoPub SDK is 5.9.0 but 5.10.0 fix a huge crash in MPTableViewAdPlacer and MPCollectionViewAdPlacer.

Regards,

**Comment by maninomula** [comment]
Hello @charliefancelli, We have just released MoPub adapter version 5.10.0.0 today.

**Comment by maninomula** [comment]
Thanks for bringing up the issue. Closing now as the adapter is released.
