### ISSUE TITLE
Swift Package Manager support

### ISSUE THREAD

**Issue by ksloginov** [googleads/googleads-mobile-ios-mediation#172]
We - as many others - are actively working to phase out cocoapods in our project. 

Is there any chance to see `GoogleMobileAdsMediationFacebook` distributed through Swift Package Manager (https://github.com/apple/swift-package-manager)?

**Comment by galip91** [comment]
Hi! Any news on this? 🙂

**Comment by ericleich** [comment]
No updates and no short term plans to do so unfortunately. The Google Mobile Ads SDK would be the first library to move to Swift package manager before we consider doing the same for mediation adapters, and there hasn't yet been movement on the GMA SDK side of things either.

**Comment by saldous** [comment]
any update on this? Google Mobile Ads SDK now supports Swift Package Manager. GoogleMobileAdsMediationFacebook is the only think left for me to remove cocoapods from my project.

**Comment by galipGB** [comment]
> The Google Mobile Ads SDK would be the first library to move to Swift package manager before we consider doing the same for mediation adapters

[As this is not the case anymore](https://github.com/googleads/swift-package-manager-google-mobile-ads) I would like to ask to reopen this request.

Mediation libraries are the only reason we can't remove cocoapods.

**Comment by Kjuly** [comment]
Looking forward to the update.

**Comment by saldous** [comment]
4 years and still no update on this? Very frustrating

**Comment by Agnakaraara** [comment]
6 years and still no update on this? Very frustrating
