### ISSUE TITLE
Keep warning " Ad network adapter GADMAdapterFacebook implements an old API."

### ISSUE THREAD

**Issue by uranometriaw** [googleads/googleads-mobile-ios-mediation#173]
XXXX[12956:406875] <Google> Ad network adapter GADMAdapterFacebook implements an old API. Please update the adapter.

Facebook Adapter is the lastest(5.6.0).

What should I do to solve this issue?
Thanks in advanced.

**Comment by maninomula** [comment]
The old API has been removed now. Please use the next version of the adapter (which we are working right now, 5.6.1) to solve this issue.
