### ISSUE TITLE
Adaptive Banner is not centering mediated MoPub banner on iOS

### ISSUE THREAD

**Issue by yood** [googleads/googleads-mobile-ios-mediation#181]
I'm switching to Adaptive Banners and noticed that MoPub banners that do not fit the frame are not centered, and instead are aligned to the left & top.

![IMG_0425](https://user-images.githubusercontent.com/5237/72391459-272a5b80-36fb-11ea-9027-b7d8e1de3e35.jpeg)

I looked into the View Debugger in Xcode and found that the GADBannerView frame is way larger than the MoPub banner frame, and that it's aligned to the top-left. I marked up the frame sizes in the screenshot below.

<img width="168" alt="Debug Views" src="https://user-images.githubusercontent.com/5237/72391466-28f41f00-36fb-11ea-9509-dedd1292152a.png">

This is a blocking issue for us for adapting Adaptive Banners. Could you please take a look?

In my pod file:
- Google-Mobile-Ads-SDK (7.53.1)
- GoogleMobileAdsMediationMoPub (5.10.0.0):
  - Google-Mobile-Ads-SDK (>= 7.52.0)
  - mopub-ios-sdk/Core (= 5.10.0)

Tested on: iPhone 11, iOS 13.3

**Comment by sgabello** [comment]
Bumping up this issue. I'm also switching from MoPub Mediation to AdMob Mediation with adaptive banners, and this is the only reason why I have yet to release an app update.

**Comment by chlandacastro** [comment]
Hello Sgabello and Yood,  it was fixed on version 5.17.0.0
