### ISSUE TITLE
Can't Custom Mediation Adapter serve ads?

### ISSUE THREAD

**Issue by jongsu253** [googleads/googleads-mobile-ios-mediation#187]
Hi, I'm working for an Ads SDK company. 
I hope our sdk will be mediate through Admob.
So, I implemented the mediation adapter according to the official guide and then checked the product by using the Mediation Test Suite.

However, even though the information about the Custom Event is correctly recognized, the adapter implemented by New API did not call the initialize method. So Admob ignored the correct response to the load request because the Adapter settings were incorrect.

So I implemented and tested the Adapter using the Old API in a similar way, there's an error message saying "Ad network adapter ** implements an old API. Please update the adapter." 

The old API worked on Android, but on iOS, it couldn't. I wonder what should I do to serve ads through custom mediation adapter?

**Comment by ericleich** [comment]
Here we are in mid-2021, and it's true that custom event still doesn't call the initialize method. It was out of scope for custom events on the new API initially. This is on the roadmap though for later this year.

Any message saying "Adapter ** implements an old API. Please update the adapter" must mean you tried to implement some long deprecated method that was part of the old API, before the old API itself was deperecated. Even today, GADCustomEventBanner and GADCustomEventInterstitial should still work in v8.x.x for iOS, but GADMediationAdapter should also work (save for the init call feature).
