### ISSUE TITLE
Latest MoPub adapter is failing to show banners

### ISSUE THREAD

**Issue by polmum** [googleads/googleads-mobile-ios-mediation#220]
I am getting the following error when trying to show a MoPub banner:
`Error Domain=5.12.0.0 Code=104 "The loaded ad is not large enough to match the requested banner size. To allow smaller banner sizes to fill a larger request, pass a GADMoPubNetworkExtras object to your ad request and set the minimumBannerSize property. Loaded ad size: {320, 50}, requested size: kGADAdSizeBanner"`

Which i think is a bug, because this worked perfectly in the previous adapter version, and because if I print kGADAdSizeBanner I get a {320, 50} size.

**Comment by polmum** [comment]
I'm sorry, I'm not a fan of bumping my own issues, but is there any news on this?

**Comment by joshuajplagonera** [comment]
Hi @polmum 
Thank you for your patience. I was able to reproduce this issue on my end.
We will send out a fix for this shortly, with a new version of the adapter.

**Comment by joshuajplagonera** [comment]
Hi @polmum 
The fix should be live with version 5.12.0.1 of the iOS adapter.
Kindly let us know if you still experience the issue on the latest iOS adapter.
