### ISSUE TITLE
InMobi adapter's transitive dependency uses UIWebView 

### ISSUE THREAD

**Issue by polmum** [googleads/googleads-mobile-ios-mediation#229]
GoogleMobileAdsMediationInMobi podspec depends on InMobiSDK, which includes Moat libraries that use UIWebView. To prevent this, the podspec should depend on InMobiSDK/Core instead.

**Comment by ericleich** [comment]
@polmum That makes sense. We're double checking with InMobi that this is appropriate solution, and that there aren't side effects of dropping the Moat dependency.

**Comment by ericleich** [comment]
We've confirmed with MoPub this is ok, and will be preparing an adapter update shortly.

**Comment by ericleich** [comment]
Starting with InMobi adapter [9.0.6.0](https://github.com/CocoaPods/Specs/blob/master/Specs/7/8/1/GoogleMobileAdsMediationInMobi/9.0.6.0/GoogleMobileAdsMediationInMobi.podspec.json#L19) we are now depending on `InMobiSDK/Core`.
