### ISSUE TITLE
GoogleMobileAds.framework 7.59.0 still use UIWebView

### ISSUE THREAD

**Issue by Astrovic** [googleads/googleads-mobile-ios-mediation#230]
I'm using GoogleMobileAds.framework 7.59.0 (https://developers.google.com/admob/ios/download).  All references to UIWebView should have been removed since version 7.55.0. But when I upload the app to iTunes Connect, it warns me that references to UIWebView have been found. 
In fact it seems that it has not been completely removed...

<img width="576" alt="GoogleMobileAdsSdkiOS-7 59 0" src="https://user-images.githubusercontent.com/2573811/81593693-1c898580-93c0-11ea-912e-f10ae215b3e7.png">

**Comment by ericleich** [comment]
I see you've already asked this in https://groups.google.com/forum/#!searchin/google-admob-ads-sdk/UIWebView%7Csort:date/google-admob-ads-sdk/QuZMbjIyxn8/dPabcepFAwAJ, that is the appropriate place for this question.

The mediation adapters themselves (this repo) do not use UIWebView.
