### ISSUE TITLE
GoogleMobileAdsMediationFacebook and UIWebView.

### ISSUE THREAD

**Issue by tommyyoon** [googleads/googleads-mobile-ios-mediation#234]
Can you look into this too? Thanks.

**Comment by ericleich** [comment]
The Facebook adapter itself does not reference UIWebView, and according to [Facebook Audience Network release notes](https://developers.facebook.com/docs/audience-network/changelog-ios/#change--uiwebview-removed), their 5.6.0 SDK removes references to UIWebView. So 5.6.0.0 adapter and higher should be UIWebView free.

Note: We did notice that starting in 5.8.0, FacebookAudienceNetwork [added a dependency on FBSDKCoreKit/Basics](https://github.com/CocoaPods/Specs/blob/master/Specs/2/1/5/FBAudienceNetwork/5.8.0/FBAudienceNetwork.podspec.json#L51). I'm assuming they didn't have a regression on their end. But either way, if you're having UIWebView warnings and diagnosed it to the Facebook adapter specifically, it's something to do with the Facebook SDK or its dependency chain.
