### ISSUE TITLE
Custom Event video not playing

### ISSUE THREAD

**Issue by Ron22c** [googleads/googleads-mobile-ios-mediation#239]
Hi,
i have implemented an adapter for custom event by following the steps provided. I am wrapping around my video ad (UIVIEW) inside the SampleMediatedNativeAd type and returning. 
But in the sample app when i am receiving the GADUnifiedNativeAd type of ad from adLoader:didReceiveUnifiedNativeAd: method, the mediaContent property does not contain any video which i have returned. if i check the 'nativeAd.mediaContent.aspectRatio' property this is also 0.

**Comment by Ron22c** [comment]
@chlandacastro Hi, i am attaching the git-hub link of the project. SDks are included in that. just pull the code and build it. There is not errors its showing but i am not able to find the video in the native ad object which i am getting from the delegate. ad-unit is added in the project for testing.
Thanks
LINK: https://github.com/Ron22c/AdMobIntegration

**Comment by chlandacastro** [comment]
@Ron22c.  Hi, Noticed that this issue should be raised in the AdMob forum: https://support.google.com/admob/community/?hl=en&gpf=%23!forum%2Fgoogle-admob-help-forum"

**Comment by ericleich** [comment]
@Ron22c It doesn't sound like an issue with the custom event example in this repo, but an issue with your specific custom event implementation that may not be working. The developer forum at https://groups.google.com/group/google-admob-ads-sdk is actually the best place to get support for your issue, where https://support.google.com/admob/community is more for AdMob product support.
