### ISSUE TITLE
Selim Bakdemir

### ISSUE THREAD

**Issue by selim1377** [googleads/googleads-mobile-ios-mediation#25]
When i try to add the adapter via cocoapods:

pod 'GoogleMobileAdsMediationAdColony', '3.2.1.1'

the project can not be build via XCode 8.x, because of linking missing frameworks.

When i investigate AdColonyFramework, it is build and linked against 'FileProvider.framework', which i dont have in XCode 8.x SDK.

Library needs to be updated to be compatible XCode 8.x too.

**Comment by maninomula** [comment]
Please use the xcode setup mentioned in this document [https://github.com/AdColony/AdColony-iOS-SDK-3/wiki/Xcode-Project-Setup](https://github.com/AdColony/AdColony-iOS-SDK-3/wiki/Xcode-Project-Setup).

**Comment by maninomula** [comment]
Closing this issue as it is inactive for more than 30 days.
