### ISSUE TITLE
GADMAdapterFacebook doesn't call adapterWillLeaveApplication event anymore

### ISSUE THREAD

**Issue by vokruttabtale** [googleads/googleads-mobile-ios-mediation#250]
The last version of GADMAdapterFacebook doesn't call adapterWillLeaveApplication anymore, so we don't now in GADInterstitialDelegate when user clicked on the interstitial ad.
It was removed in this commit https://github.com/googleads/googleads-mobile-ios-mediation/commit/7dcda71c37554c7f942420cda64b174aaa0e2320
Can you check and fix it, please?

**Comment by chlandacastro** [comment]
Thanks for reaching out.  After testing it the non-OB Interstitial ads and indeed are not calling adapterWillLeaveApplication.  We will fix it soon.

**Comment by chlandacastro** [comment]
@vokruttabtale  the fix for this issue is now live on Facebook Adapter 5.10.1.0.

**Comment by vokruttabtale** [comment]
Great, thanks!
