### ISSUE TITLE
GoogleMobileAdsMediationFacebook 5.10.1.0 pod missing

### ISSUE THREAD

**Issue by polmum** [googleads/googleads-mobile-ios-mediation#255]
Hey
You recently released a new GoogleMobileAdsMediationFacebook adapter, fixing a critical crash. But for some reason the pod is not published in the spec repo.

**Comment by ericleich** [comment]
@polmum it's coming shortly, possibly by EOD but if not today then on Monday. Facebook did a version bump PR for us which makes the release notes look like it's released, but we're still finalizing our internal testing process to verify there are no regressions. So the pod (and any backing .zip file with the framework) aren't actually released yet.

**Comment by ericleich** [comment]
Returning here to let you know that I apologize we didn't hit the Monday timeline I promised above. Having said that, we are on track for release tomorrow.

**Comment by chlandacastro** [comment]
@polmum   GoogleMobileAdsMediationFacebook 5.10.1.0 is now live.

**Comment by ericleich** [comment]
Indeed, live at https://github.com/CocoaPods/Specs/blob/master/Specs/4/1/b/GoogleMobileAdsMediationFacebook/5.10.1.0/GoogleMobileAdsMediationFacebook.podspec.json
