### ISSUE TITLE
Missing latest adapter versions

### ISSUE THREAD

**Issue by polmum** [googleads/googleads-mobile-ios-mediation#258]
Ironsource 6.18.0.1.0 and Fyber 7.6.0.0 are not published, even though the changelog for each adapter says otherwise.

If this is intended (ie, the adapters are not yet ready to be released) it would be nice to say so in the changelog.

**Comment by chlandacastro** [comment]
@polmum,  IronSource 6.18.0.1.0 is published now, and Fyber 7.6.0.0 will be available today.   We release the Adapters in a two-steps process, and the second step could take a little bit longer since it  also has to be fully reviewed before releasing.

**Comment by polmum** [comment]
Great, thanks for the update!
Is it perhaps possible to only update the changelog when the update is ready to be used then?

**Comment by chlandacastro** [comment]
@polmum 
Unfortunately, the ChangeLog file is on the first step of the process.  
Usually the release between them is not more than 24 hours apart.

**Comment by polmum** [comment]
Oh, ok. It's not ideal, especially in cases with a delay like Fyber's, but ok, I understand.
Thanks!
