### ISSUE TITLE
Vungle rewarded adapter is closing without calling userDidEarnReward

### ISSUE THREAD

**Issue by polmum** [googleads/googleads-mobile-ios-mediation#267]
When mediating Vungle, the ads are getting dismissed without a call to `userDidEarnReward`.
Checking the adapter code, what might be happening is that Vungle is calling the `vungleDidCloseAdForPlacementID` method, where the `GADMAdapterVungleRouter` class is removing the delegate, before calling the `vungleRewardUserForPlacementID` method, which is unable to reward the user as the delegate has already been removed.

**Comment by chlandacastro** [comment]
Hello Polmum.   On my testing app, userDidEarnReward is called correctly, at the end of the Video ad.   What Adapter and Vungle SDK are you using?   Could you send me a zip file of your app so I can test it.   Thanks for reaching out.

**Comment by polmum** [comment]
It happens with the latest adapter.
It might not happen always though, as it really depends on Vungle calling the rewarded method before or after the ad is closed, and that might depend on the specific ad creative being shown.
In older adapter versions this could never happen as the closed callback was the one granting the reward to the user.

I'll try to make a sample project, but by checking the adapter code you can see that this will happen if vungle grants the reward after the ad is closed.

**Comment by polmum** [comment]
I used the mediation example in this repo, using an adunit that had vungle configured, and was able to reproduce the issue: the `userDidEarnReward` was never called.
If in your example you are not seeing this issue, it might depend on the vungle ad, as I suggested.

**Comment by polmum** [comment]
Hmm, after further investigation, we think the issue is that we were using interstitial vungle placements instead of rewarded. This worked before because the reward was being granted in the closed callback, but doesn't work now.
I'm closing the issue
