### ISSUE TITLE
MoPub iOS SDK 5.14 is available; Needs support here.

### ISSUE THREAD

**Issue by granoff** [googleads/googleads-mobile-ios-mediation#269]
MoPub has released v5.14 of their SDK with specific and important support for iOS14. 

Please update the MoPob Google Ads/Admob adapater for MoPub to use the latest MoPub SDK. Thanks!

**Comment by chlandacastro** [comment]
Hi Granoff!   MoPub 5.14.0.0 and 5.14.1.0 are live now.   
Sorry for the delay.  
Regards.
Christian.

**Comment by granoff** [comment]
Thank you!
