### ISSUE TITLE
Many crashes reported to Firebase: GADMAdapterAppLovinMediationManager

### ISSUE THREAD

**Issue by glancashire** [googleads/googleads-mobile-ios-mediation#276]
Dear Developers

There are a lot of crashes caused by the Applovin mediation adapter.
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000018f4fdd0

I am using the latest releases installed via cocoapod.
- GoogleMobileAdsMediationAppLovin (6.14.6.0):
    - AppLovinSDK (= 6.14.6)
    - Google-Mobile-Ads-SDK (>= 7.67.0)

Kind Regards
Graham

<img width="1375" alt="Screenshot 2020-11-02 at 10 48 58" src="https://user-images.githubusercontent.com/314516/97854227-7593ff80-1cf9-11eb-9103-0429bd8ecedb.png">
<img width="1310" alt="Screenshot 2020-11-02 at 10 49 13" src="https://user-images.githubusercontent.com/314516/97854233-79c01d00-1cf9-11eb-80b9-c8d5c61e287b.png">
<img width="1289" alt="Screenshot 2020-11-02 at 10 49 21" src="https://user-images.githubusercontent.com/314516/97854238-7a58b380-1cf9-11eb-8d03-be5d1aa4fb25.png">
<img width="1254" alt="Screenshot 2020-11-02 at 10 49 32" src="https://user-images.githubusercontent.com/314516/97854239-7a58b380-1cf9-11eb-8549-a0041b3dab19.png">

**Comment by chlandacastro** [comment]
Hello glancashire!  I was not able to replicate these crashes, could you send me the steps to replicate it?
Thanks.

**Comment by glancashire** [comment]
Dear Chlandacastro

I have not been able to replicate the issue, but I get many of these errors from several of our production apps.

I have posted logs and screenshots.

From what I read there seems to be a problem when Applovin Ads are shown and afterwards on “destruction” an memory management error occurs. 

Kind Regards

Graham Lancashire

**Comment by ericleich** [comment]
@glancashire sorry for the delayed response on this. The stack trace does indicate that the crashing line occurs within some block within [GADMAdapterAppLovinMediationManager.m](https://github.com/googleads/googleads-mobile-ios-mediation/blob/master/adapters/AppLovin/AppLovinAdapter/GADMAdapterAppLovinMediationManager.m). We've taken a close look over it and got a second opinion internally, and believe that we're handling memory ok in that class.

Our only logical conclusion is that some other code outside the adapter binary may be messing with this memory space causing this code to crash, but that's undiagnosable. The crash insight from the report actually mentions the same thing. So, unfortunately, we're closing this as won't fix/infeasible.
