### ISSUE TITLE
Crash in GADMAdapterUnity.m 

### ISSUE THREAD

**Issue by GabeJacobs** [googleads/googleads-mobile-ios-mediation#281]
Hi there,

I'm running an objective-c project with the following pod versions:
Google-Mobile-Ads-SDK (7.68.0)
GoogleMobileAdsMediationUnity (3.5.0.0)

Crashlytics has reported a crash with many of my users:

> Crashed: com.apple.main-thread
> EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000010

> Crashed: com.apple.main-thread
0  Fart World                     0x101210b94 -[GADMAdapterUnity initializationComplete] + 179 (GADMAdapterUnity.m:179)
1  Fart World                     0x10123bea0 +[USRVSdkProperties notifyInitializationComplete] + 85 (USRVSdkProperties.m:85)
2  libdispatch.dylib              0x182f83298 _dispatch_call_block_and_release + 24
3  libdispatch.dylib              0x182f84280 _dispatch_client_callout + 16
4  libdispatch.dylib              0x182f3305c _dispatch_main_queue_callback_4CF$VARIANT$mp + 896
5  CoreFoundation                 0x1832cb5d0 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
6  CoreFoundation                 0x1832c5a78 __CFRunLoopRun + 2480
7  CoreFoundation                 0x1832c4b90 CFRunLoopRunSpecific + 572
8  GraphicsServices               0x1995e7598 GSEventRunModal + 160
9  UIKitCore                      0x185bae638 -[UIApplication _run] + 1052
10 UIKitCore                      0x185bb3bb8 UIApplicationMain + 164
11 Fart World                     0x100b64318 main + 20 (main.m:20)
12 libdyld.dylib                  0x182fa3588 start + 4

**Comment by chlandacastro** [comment]
Hello GabeJacobs!  When did you update to Google-Mobile-Ads-SDK (7.68.0) and GoogleMobileAdsMediationUnity (3.5.0.0)?   The 11/25/2020 we updated the code but we just updated UnityAdapter v3.5.1.0 Cocoapod and Bintray earlier today.    We have another issue similar at yours,  https://github.com/googleads/googleads-mobile-ios-mediation/issues/282
Regards, 
Christian.

**Comment by ericleich** [comment]
Fixed with https://github.com/googleads/googleads-mobile-ios-mediation/pull/283, will be in a 3.5.1.1 patch release.
