### ISSUE TITLE
UnityAdapter-3.5.1.0

### ISSUE THREAD

**Issue by qbit86** [googleads/googleads-mobile-ios-mediation#282]
Hi,

UnityAdapter-3.5.**1**.0 is still not listed here: https://bintray.com/google/mobile-ads-adapters-ios/UnityAdapter
While [Changelog](https://github.com/googleads/googleads-mobile-ios-mediation/blob/master/adapters/Unity/CHANGELOG.md) says it is ready.
When will UnityAdapter-3.5.1.0 be available for downloading?

At the moment I have crashes in `-[GADMAdapterUnity initializationComplete]`, probably due to the version mismatch between UnityAds-3.5.1 and UnityAdapter-3.5.**0**.0.

**Comment by chlandacastro** [comment]
Hello qbit86,  UnityAdapter v3.5.1.0 is live now.   Cocoapod and Bintray was updated earlier today.  
Regards, 
Christian.

**Comment by chlandacastro** [comment]
Hello again qbit86!  We just received a PR from Unity to fix a crash issue.  Perhaps this is what is affecting your app.  I'll keep you posted.
Regards,
Christian

**Comment by qbit86** [comment]
@chlandacastro Thanks a lot for letting me know!
So, when will 3.5.1.**1** be available here? https://bintray.com/google/mobile-ads-adapters-ios/UnityAdapter

/cc @ericleich @AliceNoWonderland

**Comment by chlandacastro** [comment]
Hello qbit86! We just released the new Unity iOS Adapter v3.5.1.1 it is live now.    
From the Changelog: - Fixed a crash that sometimes occurred when the Unity Ads SDK finished initializing.
Regards, 
Christian.
