### ISSUE TITLE
Admob Adapter doesn't recognize Dynamic FAN SDK.

### ISSUE THREAD

**Issue by pieomy** [googleads/googleads-mobile-ios-mediation#287]
Hi,

I am Delphi user and I added Facebook Audience Network Dynamic SDK to my project. and also I added Admob Facebook Adapter but Adapter dosen't find FAN SDK, I can not use FAN Static SDK (our compiler have bug) so what can i do in this situation? is there a Admob Facebook Adapter dynamic version?

Thank you.

![Screen Shot 2021-01-12 at 01 28 50](https://user-images.githubusercontent.com/49295522/104245991-470f6f00-5476-11eb-87ae-08b4cbf89f7d.png)

**Comment by chlandacastro** [comment]
Hello pieom!  We don't support Delphi at this time.  Would you let us know if this is an iOS or Android issue?
Thank, 
Christian.

**Comment by pieomy** [comment]
Hi Christian,

Please forget about delphi, its iOS question. 
Can I download Dynamic Admob Facebook Adapter any where?

I need dynamic SDK. Thank you

**Comment by chlandacastro** [comment]
Hi Pieomy,   Would you clarify if is this related to XCframework?   If it is so,  we are still working on that.
Regards, 
Christian.

**Comment by chlandacastro** [comment]
HI, Pieomy,   We have updated our Facebook adapter to support XCframework,  I hope that could help.  
Regards, 
Christian

**Comment by pieomy** [comment]
Hi,

Thank you, I think it will be solve this.
