### ISSUE TITLE
MoPub mediation with configuring GDPR consent leads the app crash

### ISSUE THREAD

**Issue by idearibosome** [googleads/googleads-mobile-ios-mediation#293]
Hello.

I am using MoPub as a target network for AdMob mediation, and the GDPR consent is configured by using User Messaging Platform SDK (https://developers.google.com/admob/ump/ios/quick-start).

After serving ads for a while (about 5 minutes), the following error is occurred and the app crashes:
```
Warning: no ad unit available for GDPR sync. Please make sure that the SDK is initialized correctly via `initializeSdkWithConfiguration:completion:` as soon as possible after app startup.
```

This message is declared in ```MPConsentManager.m``` of the MoPub SDK (https://github.com/mopub/mopub-ios-sdk/blob/5.15.0/MoPubSDK/Internal/MPConsentManager.m#L570).

The reason why it happens is as follows.
- When the app starts, the AdMob SDK calls ```GADMediationAdapterMoPub.adSDKVersion```, and the ```MoPub.sharedInstance``` is initialized ([Code link](https://github.com/googleads/googleads-mobile-ios-mediation/blob/982ed7de7a1ed2e44e0d6eb5140b3b7d6ecf5c88/adapters/MoPub/MoPubAdapter/GADMediationAdapterMoPub.m#L36)).
- The initialization code of the ```MoPub``` instance calls ```handlePersonalData```, which creates the ```MPConsentManager.sharedManager```. ([Code link](https://github.com/mopub/mopub-ios-sdk/blob/5.15.0/MoPubSDK/MoPub.m#L181)).
- The initialization code of the ```MPConsentManager``` instance calls ```newNextUpdateTimer```, which creates a ```MPTimer``` object ([Code link](https://github.com/mopub/mopub-ios-sdk/blob/5.15.0/MoPubSDK/Internal/MPConsentManager.m#L654)).
- After a while (maybe 5 minutes), the timer is fired and it calls ```synchronizeConsentWithCompletion``` ([Code link](https://github.com/mopub/mopub-ios-sdk/blob/5.15.0/MoPubSDK/Internal/MPConsentManager.m#L667)).
- Because the MoPub is not initialized (i.e., ```initializeSdkWithConfiguration:completion:``` is not called yet, as mentioned in the error message), no ad unit is specified and therefore the error occurs ([Code link](https://github.com/mopub/mopub-ios-sdk/blob/5.15.0/MoPubSDK/Internal/MPConsentManager.m#L569)).

Is there any way to enforce the AdMob SDK to initialize the mediated SDKs? (e.g., calling ```setUpWithConfiguration:completionHandler:``` as in [this code link](https://github.com/googleads/googleads-mobile-ios-mediation/blob/982ed7de7a1ed2e44e0d6eb5140b3b7d6ecf5c88/adapters/MoPub/MoPubAdapter/GADMediationAdapterMoPub.m#L15))

Thanks!

**Comment by ericleich** [comment]
@idearibosome AdMob calls the `setUpWithConfiguration:completionHandler:` method once your app calls [startWithCompletionHandler:](https://developers.google.com/admob/ios/api/reference/Classes/GADMobileAds#-startwithcompletionhandler:) on GADMobileAds. If your app doesn't initialize AdMob, AdMob won't initialize 3p SDKs. There's some documentation on this [here](https://developers.google.com/admob/ios/quick-start#initialize_the_mobile_ads_sdk). Additionally, to guarantee that MoPub's adapter has been called and has been fully initialized, the recommendation is to wait for AdMob's init callback to come through as documented [here](https://developers.google.com/admob/ios/mediate#initialize_the_mobile_ads_sdk).
