### ISSUE TITLE
Vungle iOS Adapter v6.9.1.0

### ISSUE THREAD

**Issue by vokruttabtale** [googleads/googleads-mobile-ios-mediation#295]
Vungle iOS Adapter updated to v6.9.1.0 here 2 days ago and on the page [https://developers.google.com/admob/ios/mediation/vungle](https://developers.google.com/admob/ios/mediation/vungle) you added info about this version. But on cocoapods still available only the previous version 6.8.1.1. When are you going to publish it so we can use it?

**Comment by chlandacastro** [comment]
Hello Vokruttabtale!  Vungle iOS Adapter 6.9.1.0 was published last Friday. 
Regards, 
Christian.
