### ISSUE TITLE
Prebuilt versions of the Facebook and MoPub adapters are still the old version in CocoaPods and BinTray

### ISSUE THREAD

**Issue by smartestapps** [googleads/googleads-mobile-ios-mediation#303]
The Facebook adapter updated to 6.3.1.0 as of five days ago, but the prebuilt versions are still 6.3.0.0.

The MoPub adapter updated to 5.16.2.0 as of five days ago, but the prebuilt versions are still 5.16.1.0.

**Comment by chlandacastro** [comment]
Hello Smartestapps!   As your probably know, Bintray services will be deprecated soon,  we are making some  internal changes.   For Facabook and MoPub  Cocopod  updates, they will be available either today or tomorrow. I will keep you post it once  they are live.   
Regards, 
Christian,.

**Comment by chlandacastro** [comment]
Hello  Smartestapps! FAN 6.3.1.0 and MoPub 5.16.2.0 are now live.   We are not longer updating Bintray.  If you need the links to the zip files.  
https://dl.google.com/googleadmobadssdk/mediation/ios/facebook/FacebookAdapter-6.3.1.0.zip
https://dl.google.com/googleadmobadssdk/mediation/ios/mopub/MoPubAdapter-5.16.2.0.zip
We will update the documentation soon.
Rewards, 
Christian.

**Comment by chlandacastro** [comment]
Hi Smartestapps!  Now you can download the zip file directly from here. 
 https://developers.google.com/admob/ios/mediation/facebook#facebook-ios-mediation-adapter-changelog

Regards, 
Christian .
