### ISSUE TITLE
FacebookAdapter forbidden download

### ISSUE THREAD

**Issue by iDevid** [googleads/googleads-mobile-ios-mediation#313]
When trying to do `pod install` the console will give this error:
```
Installing GoogleMobileAdsMediationFacebook (6.2.1.0)
[15:37:24]: ▸ [!] Error installing GoogleMobileAdsMediationFacebook
[15:37:24]: ▸ [!] /usr/bin/curl -f -L -o /var/folders/wp/4pf4qdmn217djs68lskdcc780000gn/T/d20210426-2187-1kg782/file.zip https://google.bintray.com/mobile-ads-adapters-ios/FacebookAdapter/6.2.1.0/FacebookAdapter-6.2.1.0.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.10.1 cocoapods-downloader/1.4.0'
[15:37:24]: ▸ % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[15:37:24]: ▸ Dload  Upload   Total   Spent    Left  Speed
[15:37:24]: ▸   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[15:37:24]: ▸ curl: (22) The requested URL returned error: 403 Forbidden
```

Seems to be an error related to file at `https://google.bintray.com/mobile-ads-adapters-ios/FacebookAdapter/6.2.1.0/FacebookAdapter-6.2.1.0.zip` that is forbidden.

**Comment by jjhampton** [comment]
Looks like we have to update to the FacebookAdapter 6.3.0 or higher to get around this?

https://github.com/CocoaPods/Specs/blob/master/Specs/4/1/b/GoogleMobileAdsMediationFacebook/6.3.0.0/GoogleMobileAdsMediationFacebook.podspec.json

One issue is that updating to that version of the FacebookAdapter requires updating the iOS GAM SDK to 8.1.0, which some users may not be ready to do: 

```
  "dependencies": {
    "FBAudienceNetwork": "6.3.0",
    "Google-Mobile-Ads-SDK": ">= 8.1.0"
  },
```

Is there any way we can still install Facebook Adapter 6.2.0 without updating to iOS GAM SDK to 8.1.0 ?

**Comment by jjhampton** [comment]
@iDevid The 403 forbidden is due to Bintray being sunset:
* https://status.bintray.com/
* https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

As of May 1 it looks like it'll be deprecated and today is just a temporary 'warning' outage to prepare users.

**Comment by iDevid** [comment]
Thank you for the clarification :)

**Comment by ericleich** [comment]
Also relevant: https://github.com/googleads/googleads-mobile-ios-mediation/issues/311

Despite CocoaPods documentation that a deleted version can't be re-added, the tool lets me. Most adapters' latest versions are off of bintray, but we haven't done anything to migrate older versions yet.

Are you seeing consistent failures, or was this just a one-time warning? I wasn't planning to try backporting anything until after bintray confirmed stopped serving on May 1st.

**Comment by jjhampton** [comment]
@ericleich Yes, it was consistent failures during the `pod install` step as @iDevid mentioned above - 403 Forbidden error responses, but only during the time period of the scheduled outage on Bintray from April 26th 6AM to 2PM PDT, which was intended to warn/prepare users for the permanent Bintray outage on May 1: https://status.bintray.com/incidents/kh3zbvqkvj2c

Installs using the existing Bintray URLs (such as the https://google.bintray.com/mobile-ads-adapters-ios/FacebookAdapter/6.2.1.0/FacebookAdapter-6.2.1.0.zip URL) work now as of April 28, since the one-time outage is over with, but on May 1 they'll no longer work.

**Comment by ericleich** [comment]
We updated the last 12 months of adapters to use new downloads that we're hosting, but it looks like from [bintray sunset announcement](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) that they decided to let old payloads exist indefinitely. So at this point, there shouldn't be any disruption to your workflow unless we made an error when updating old podspecs. Please open a new issue if you find one that isn't working.
