### ISSUE TITLE
Please include arm64-simulator slices in .xcframework

### ISSUE THREAD

**Issue by sgabello** [googleads/googleads-mobile-ios-mediation#329]
To fix warnings and errors in Xcode on M1 Macs.

**Comment by chlandacastro** [comment]
The Following are the updated adapters that include arm64-simulator slice. 
AppLovin 4.7.2.1 ,Chartboost 8.5.0.2, Facebook 6.9.0.1, i-Mobile 2.2.0.1,  MoPub 5.18.2.1,

**Comment by chlandacastro** [comment]
As of Wednesday, March 4, 2022. The Followings are the updated adapters that include the arm64-simulator slice:
AdColony 4.7.2.2
AppLovin 11.1.2.0
Chartboost 8.5.0.2,
Facebook 6.9.0.1,
i-Mobile 2.2.0.1,
inMobi 10.0.2.1
nend 7.2.0.0
Maio 1.6.0.1
MoPub 5.18.2.1.
MyTarget 5.15.0.1
Tapjoy 12.0.0.1
Unity 4.0.0.0
VerizonMedia 1.14.1.1
