### ISSUE TITLE
Error Forbidden when install GoogleMobileAdsMediationAdColony in iOS

### ISSUE THREAD

**Issue by hzung** [googleads/googleads-mobile-ios-mediation#331]
I added this line to my Podfile

```
pod 'GoogleMobileAdsMediationAdColony', '3.3.7.3'
```
Then `pod install`

This error keeps appearing.

```
[!] Error installing GoogleMobileAdsMediationAdColony
[!] /usr/bin/curl -f -L -o /var/folders/_s/6tnw95hs5gb8msfqxmmm0fc40000gp/T/d20210906-36824-52c5sb/file.zip https://google.bintray.com/mobile-ads-adapters-ios/AdColonyAdapter/3.3.7.3/AdColonyAdapter-3.3.7.3.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.11.0 cocoapods-downloader/1.5.0'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 403 Forbidden
```

I try to access the link `https://google.bintray.com/mobile-ads-adapters-ios/AdColonyAdapter/3.3.7.3/AdColonyAdapter-3.3.7.3.zip` but it keeps saying "Forbidden!"

Please help!

**Comment by chlandacastro** [comment]
Him Hzung!  A few month ago Bintray when sunset and the AdColony Mediation Adapter now is supported starting in version 4.1.5.0  https://developers.google.com/admob/ios/mediation/adcolony#adcolony-ios-mediation-adapter-changelog.   Let me know if you need further assistance.

**Comment by hzung** [comment]
@chlandacastro Thanks, man. I changed the version to 4.1.5.0, and it worked!
