### ISSUE TITLE
requestInterstitialAdWithParameter / GADCustomEventInterstitial not called

### ISSUE THREAD

**Issue by rcorin** [googleads/googleads-mobile-ios-mediation#34]
I've created two adUnits on the Admob console, one for a banner and one for an interstitial, and created custom events for both. While the Banner works correctly and the custom class gets called, the interstitial one isn't being triggered, and the function requestInterstitialAdWithParameter is never called. The docs don't mention any difference between the banners and the interstitials so I'm baffled of what might be going wrong... any help / suggestion is welcome.
regards

**Comment by maninomula** [comment]
Now there are separate documentation for Interstitial and Banner Ads. Please refer to the links below:
[https://developers.google.com/admob/android/banner](https://developers.google.com/admob/android/interstitial)
[https://developers.google.com/admob/android/banner.](https://developers.google.com/admob/android/banner)
Also please take reference from the examples provided in this [repository.](https://github.com/googleads/googleads-mobile-ios-examples)

**Comment by maninomula** [comment]
Please get back to us if you have any other issue.

Thanks

**Comment by maninomula** [comment]
Closing this issue as it is inactive for more than 30 days.
