### ISSUE TITLE
The latest SDK failed to launch app.

### ISSUE THREAD

**Issue by Estejin** [googleads/googleads-mobile-ios-mediation#340]
I can not launch app with the latest SDK.
 Library not loaded: @rpath/FBSDKCoreKit_Basics.framework/FBSDKCoreKit_Basics

My pod installed the following, how to solve this problem, please help me. Thanks a lot.

Installing FBAudienceNetwork (6.8.0)
Installing FBSDKCoreKit_Basics (12.0.2)
Installing Google-Mobile-Ads-SDK (8.12.0)
Installing GoogleAppMeasurement (8.9.0)
Installing GoogleMaps (5.2.0)
Installing GoogleMobileAdsMediationFacebook (6.8.0.0)

Installing GoogleUserMessagingPlatform (2.0.0)
Installing GoogleUtilities (7.6.0)
Installing PromisesObjC (2.0.0)
Installing nanopb (2.30908.0)

**Comment by chlandacastro** [comment]
Hi @Estejin  could you let me know the status of your issue?  I re-tested  our adapter and I wasn't able to duplicate this issue.   I am also getting the same dependencies Installing FBAudienceNetwork (6.8.0)
Installing FBSDKCoreKit_Basics (12.1.0)
Installing Google-Mobile-Ads-SDK (8.12.0)
Installing GoogleAppMeasurement (8.9.1)
Installing GoogleMobileAdsMediationFacebook (6.8.0.0)
Installing GoogleUserMessagingPlatform (2.0.0)
Installing GoogleUtilities (7.6.0)
Installing PromisesObjC (2.0.0)
Installing nanopb (2.30908.0)
Regards,
Christian.

**Comment by rojo69** [comment]
Not sure if it's the same issue, but for me a 'pod update' downgrades some libs and ends up with duplicate UUIDS.

...
Installing FBSDKCoreKit 9.3.0 (was 11.2.1)
Installing FBSDKCoreKit_Basics 12.1.0 (was 11.2.1)
Installing FBSDKLoginKit 9.3.0 (was 11.2.1)
Installing FirebaseFacebookAuthUI 11.0.3 (was 12.0.0)
Removing FBAEMKit
Generating Pods project
Integrating client project
Pod installation complete! There are 21 dependencies from the Podfile and 43 total pods installed.

[!] [Xcodeproj] Generated duplicate UUIDs:

**Comment by chlandacastro** [comment]
Hi @Estejin and @rojo69 since I was not able to replicate this issue, could you send me a the app in a zip file so I can try it.  And also could you send me your Podfile?
Regards, 
Christian.

**Comment by rojo69** [comment]
I'm afraid I can't do that, @chlandacastro. It is a commercial app.
However my issues went away after specifying min version number on another Facebook related pod.
`pod 'FirebaseUI/Facebook', '~> 12.0'`

**Comment by chlandacastro** [comment]
Hi @Estejin  could you also follow add,  pod 'FirebaseUI/Facebook', '~> 12.0'   as @rojo69 did.   Let me know if what work for you.
