### ISSUE TITLE
Google ads can't be clicked

### ISSUE THREAD

**Issue by xabodog** [googleads/googleads-mobile-ios-mediation#346]
I put a lot of ads in UICollectionView, GADBannerView's click event agent - (void) adViewWillLeaveApplication: (GADBannerView) adView by UICollectionView click event - (void) collectionview: (UICollectionView) CollectionView didSelectItemAindExPath: (NSIndexPath)indexPath is overwritten, resulting in Google ads can not click, what is the solution?

**Comment by chlandacastro** [comment]
HI Xabodog!  Could you specify with version of the SDK you are using, the Xcode version, also I want to know if you are using one of our adapters.  
Regards,
Christian,
