### ISSUE TITLE
Custom adapter. Empty reward type and amount in userDidEarnRewardHandler

### ISSUE THREAD

**Issue by fotism23** [googleads/googleads-mobile-ios-mediation#347]
Hello

We are trying to build a Custom AdMob Adapter and when we want to reward a user we invoke the `GADMediationRewardedAdEventDelegate.didRewardUserWithReward` passing a `GADAdReward` object with `type` and `amount`. 
The reward arriving in the host application's `userDidEarnRewardHandler` of `GADRewardedAd.present` method, has empty `type` and `amount` equals to 1. 
If we chose to override those values from AdMob dashboard in placement settings the reward has the correct values as specified in the dashboard, but this approach does not fit in our case.

Below is an example of the Adapter `didRewardUserWithReward` method

```objc
- (void) onAdCompleteExample:(RewardInfo *)rewardInfo
{
    NSDecimalNumber *rewardValue = [NSDecimalNumber decimalNumberWithString:@"1500"];
    NSString *rewardName = [rewardInfo name];
    
        GADAdReward *adReward = [[GADAdReward alloc] initWithRewardType:rewardName rewardAmount:rewardValue];
        
        id<GADMediationRewardedAdEventDelegate> strongDelegate = self->_adEventDelegate;
        
        [strongDelegate didEndVideo];
        [strongDelegate didRewardUserWithReward:adReward];
}
```

Host App example

```swift
@IBAction func showRewardedAd(_ sender: Any) {
        if (rewardedAd != nil) {
            rewardedAd?.present(fromRootViewController: self) {
                let reward = self.rewardedAd!.adReward
                print("Reward received with currency \(reward.type), amount \(reward.amount)")
            }
        } else {
            print("Ad wasn't ready")
        }
    }
```

We get the following log

`Reward received with currency , amount 1`

We have tried various approaches regarding the `adEventDelegate` and `DecimalNumber` initialization as found in the example and other network adapters such as [here](https://github.com/googleads/googleads-mobile-ios-mediation/blob/3284434c2c702e342d28dbe04186f1862f843661/example/CustomEvent/SampleCustomEventRewarded.m) and [here](https://github.com/googleads/googleads-mobile-ios-mediation/blob/818e7dd7d231860930566b9000bcb4d060e3e7f6/example/Adapter/SampleAdapter.m), but nothing works. We have also tried to dispatch the didRewardUserWithReward in the main thread with no luck. 

The above works as expected on Android.

Is something wrong from our side or is it an issue on AdMob?

**Comment by chlandacastro** [comment]
HI @fotism23  for reaching out!  I have also tested our adapters and I got the same results that yours .  And after checking our documentation about this issue,  it is not possible to overwrite the [amount](https://developers.google.com/admob/ios/api/reference/Classes/GADAdReward#/c:objc(cs)GADAdReward(im)initWithRewardType:rewardAmount:) value.   In the  Admob UI it amount can only be overrides rewarded settings provided by third-party ad networks as you can see it in the  [instructions to create a rewarded ad](https://support.google.com/admob/answer/7311747) if you have more questions let us know. 
Regards, 
Christian.

**Comment by fotism23** [comment]
Hi @chlandacastro Thanks you for the response. The strange thing is that on Android you can specify the reward amount and reward type on the adapter side.

**Comment by ericleich** [comment]
@fotism23 While it sounds like there may be a bug in the iOS implementation, it is not a commonly used feature. We have been considering moving away altogether from the AdMob UI option to allow you to have 3p networks override the ad unit's reward. If that UI feature is removed, it would also render this bug not applicable.

Can you explain your use case for why you would want to reward differently from your custom event? Why does the ad source matter?

If you really have a need to reward differently per adapter, you could ignore the value  Note that as a workaround, if you wanted to do this, you could ignore the amount from the `userDidEarnRewardHandler` in the [present](https://developers.google.com/admob/ios/api/reference/Classes/GADRewardedAd#-presentfromrootviewcontroller:userdidearnrewardhandler:) call, and look at the [adNetworkClassName](https://developers.google.com/admob/ios/api/reference/Classes/GADResponseInfo.html#adnetworkclassname) field from the `GADRewardedAd.responseInfo` object.

**Comment by ericleich** [comment]
Closing issue for now due to no response. Please do respond if you'd like to discuss a use case.
