### ISSUE TITLE
AppLovin adapter - Native ads format support

### ISSUE THREAD

**Issue by igorvoytovich** [googleads/googleads-mobile-ios-mediation#348]
Hello,

Starting from version 11 AppLovin supports native ad format.
(https://github.com/AppLovin/AppLovin-MAX-SDK-iOS/releases/tag/release_11_0_0)
(https://dash.applovin.com/documentation/mediation/ios/getting-started/native-manual)
(https://dash.applovin.com/documentation/mediation/ios/getting-started/native-templates)

As far as I can see, the AppLovin adapter has already been updated to include version 11 of the AppLovin SDK, but does not yet support the native ad format. (https://developers.google.com/admob/ios/mediation/applovin#version-11.0.0.0)

Considering the fact that MoPub is becoming a part of AppLovin and will soon stop working, I think it's worth adding support for native ads to allow developers to migrate normally from the MoPub adapter to the AppLovin adapter.

Thanks.

**Comment by chlandacastro** [comment]
Hi @igorvoytovich  for contact us!  At this time there are not plans no add Native ads to the AppLovin Adapter.
