### ISSUE TITLE
UnityAdapter is not work with version 4.0.0

### ISSUE THREAD

**Issue by onstonboy** [googleads/googleads-mobile-ios-mediation#349]
Hi, I added 2 ways:
1. pod 'GoogleMobileAdsMediationUnity'
2. add manually ver 4.0.0.0

but there are no way work.

Please help!! Thanks.

**Comment by chlandacastro** [comment]
hi @onstonboy !  I have tested it and it is working as expected.   
Could you check if the are using iOS 10 in your podfile.  platform :ios, '10.0'
without iOS 10 it will install UnityAds (3.7.5) instead of  the latest UnityAds (4.0.0)
I hope this help and let me know if you have more questions. 
![Screen Shot 2022-01-17 at 9 56 50 AM](https://user-images.githubusercontent.com/59298836/149818704-a3b825b3-3b72-4e0c-8e05-06aaf7b6df03.png)

**Comment by onstonboy** [comment]
Hi @chlandacastro, I installed ver 4.0.0 but u can see the following image. Adapter is not found in application 
<img width="566" alt="Screen Shot 2022-01-26 at 23 28 36" src="https://user-images.githubusercontent.com/22241392/151205297-2cf14e47-e761-4fbf-aa87-deaecc4130d0.png">
![image](https://user-images.githubusercontent.com/22241392/151205250-f0dd26e2-f7cb-4d17-8755-178021b19863.png)

**Comment by chlandacastro** [comment]
Hi @onstonboy!  I have tested again and I am getting the adapter initialized. However, this time I am not getting Unity's banners ads. Interstitial and rewarded ads are showing as expected.  I will investigate more about this.   Could you give me your Xcode version, iOS version,  your podfile code, and the device you are testing it in so I can have a better picture of your project. 
Thanks.

**Comment by onstonboy** [comment]
Hi @chlandacastro, my xcode's version is 12.0. ah my google_mobile_ads_sdk just got ver 8.11.0. Is it problem?

**Comment by chlandacastro** [comment]
Hi @onstonboy!  Yes it could be a problem.   Most adapters require XCode 12.5 or above.  I will recommend installing XCode 13.  But I will need more information like test devices, the iOS version number, your podfile code, the device you are testing it and more information like (i.e. time they tested it, gameID, logs, a sample app) that would help us dig into it further.  Also I like to know which was the previous working version of this app.
Thanks.

**Comment by onstonboy** [comment]
Hi @chlandacastro , oh sorry for my mistake. my xcode's version was 13.2.1 already. But i used latest google_mobile_ads from google is 1.0.1 and Google_mobile_ads_sdk(inside goog_mobile_ads library) is 8.11.0. I dont know how to upgrade it up to 8.13.0. but in this version, android side work perfectly.

**Comment by onstonboy** [comment]
![image](https://user-images.githubusercontent.com/22241392/151284470-3a977c1f-ab84-4dd7-bff9-9fa2bb0f7214.png)
Oh i tried to upgrade to 8.13.0 but still not work for me.

**Comment by joshh-devrel** [comment]
Closed as the issue wasn't reproducible on our end. Please update to the [latest UnityAds iOS adapter](https://developers.google.com/admob/ios/mediation/unity#unity-ads-ios-mediation-adapter-changelog).
