### ISSUE TITLE
GMA SDK Version 9.0.0 CocoaPods Support

### ISSUE THREAD

**Issue by ericleich** [googleads/googleads-mobile-ios-mediation#350]
With the [release](https://developers.google.com/admob/ios/rel-notes) of Google Mobile Ads SDK version 9.0.0, every adapter will require a new release with updated dependencies in CocoaPods to point to 9.x of the Google Mobile Ads SDK.

This will serve as the tracking bug for the following adapter pods:

- GoogleMobileAdsMediationAdColony (Live)
- GoogleMobileAdsMediationAppLovin (Live)
- GoogleMobileAdsMediationChartboost (Live)
- GoogleMobileAdsMediationFacebook (Live)
- GoogleMobileAdsMediationFyber (Live)
- GoogleMobileAdsMediationIMobile (Live)
- GoogleMobileAdsMediationInMobi (Live)
- GoogleMobileAdsMediationIronSource (Live)
- GoogleMobileAdsMediationMaio  (Live)
- GoogleMobileAdsMediationMoPub (Live)
- GoogleMobileAdsMediationMyTarget (Live)
- GoogleMobileAdsMediationNend (Live)
- GoogleMobileAdsMediationTapjoy (In progress)
- GoogleMobileAdsMediationUnity (Live)
- GoogleMobileAdsMediationVerizonMedia (In progress)
- GoogleMobileAdsMediationVungle (Live)

**Comment by chlandacastro** [comment]
As of Thursday, February 10, 2022. The Followings are the updated adapters that include the arm64-simulator slice: 
AppLovin 4.7.2.1, 
Chartboost 8.5.0.2, 
Facebook 6.9.0.1, 
i-Mobile 2.2.0.1,  
MoPub 5.18.2.1.

**Comment by ericleich** [comment]
Status as of February 10, 20202:

Live:
GoogleMobileAdsMediationAdColony
GoogleMobileAdsMediationAppLovin
GoogleMobileAdsMediationChartboost
GoogleMobileAdsMediationFacebook
GoogleMobileAdsMediationFyber
GoogleMobileAdsMediationIMobile
GoogleMobileAdsMediationInMobi
GoogleMobileAdsMediationIronSource
GoogleMobileAdsMediationMaio
GoogleMobileAdsMediationMoPub
GoogleMobileAdsMediationMyTarget
GoogleMobileAdsMediationNend
GoogleMobileAdsMediationUnity
GoogleMobileAdsMediationVungle

In Progress:
GoogleMobileAdsMediationTapjoy
GoogleMobileAdsMediationVerizonMedia

**Comment by chlandacastro** [comment]
Status as of February 14, 2022:

Live:
GoogleMobileAdsMediationAdColony
GoogleMobileAdsMediationAppLovin
GoogleMobileAdsMediationChartboost
GoogleMobileAdsMediationFacebook
GoogleMobileAdsMediationFyber
GoogleMobileAdsMediationIMobile
GoogleMobileAdsMediationInMobi
GoogleMobileAdsMediationIronSource
GoogleMobileAdsMediationMaio
GoogleMobileAdsMediationMoPub
GoogleMobileAdsMediationMyTarget
GoogleMobileAdsMediationNend
GoogleMobileAdsMediationUnity
GoogleMobileAdsMediationVungle
GoogleMobileAdsMediationVerizonMedia

In Progress:
GoogleMobileAdsMediationTapjoy

**Comment by ericleich** [comment]
Tapjoy is launched, closing issue!
