### ISSUE TITLE
Project doesn't compile after adding GoogleMobileAdsMediationTestSuite

### ISSUE THREAD

**Issue by sbaropeak** [googleads/googleads-mobile-ios-mediation#356]
Hi, not sure if this the right place to file an issue for this problem but I couldn't find a better one.

I've created an empty iOS App project that uses cocoapods and just adds these two pods:
```ruby
  pod 'Google-Mobile-Ads-SDK'
  pod 'GoogleMobileAdsMediationTestSuite'
```

Cocoapods resolves to these version:
- Google-Mobile-Ads-SDK: 9.3.0
- GoogleMobileAdsMediationTestSuite: 2.0.0

The project doesn't build and the linker raises these errors:
<img width="522" alt="Screenshot 2022-04-20 at 09 05 36" src="https://user-images.githubusercontent.com/82795080/164170354-c7966b86-06a5-4b44-b83c-cca34b12766b.png">

Is there something I'm doing wrong?

Thanks in advance.

**Comment by chlandacastro** [comment]
HI @sbaropeak!  I noticed you are still using the kGAD prefix.  In [Google Mobile Ads SDK 8.12.0](https://developers.google.com/admob/ios/rel-notes?hl=en) the kGAD prefix was deprecated.  You should use  those with GAD prefix instead.

**Comment by sbaropeak** [comment]
Hi @chlandacastro, thanks for your answer.

I'm not using the prefix kGAD, the project is the default iOS app from Xcode, I didn't add a single line of code. I just ran `pod init`, added the those two pods to the Podfile and then ran `pod install`.

**Comment by chlandacastro** [comment]
hi @sbaropeak !  Can you go to the AdTest code and remove the  k in kGAD.   I think that will solve this problem.   Let me know how it goes.

**Comment by sbaropeak** [comment]
Hi @chlandacastro, thanks for your response.

I have uploaded the project to a [repo](https://github.com/sbaropeak/AdTests) so you can see that there is no code using kGAD or anything at all.

Looking at the linker error in detail we can see that the references to kGAD constants are inside the GoogleMobileAdsMediationTestSuite pod:
<img width="879" alt="Screenshot 2022-04-22 at 09 52 30" src="https://user-images.githubusercontent.com/82795080/164643314-3ca0aaa2-12d4-4026-8d13-d5005ad3959d.png">

Thanks

**Comment by chlandacastro** [comment]
Hi @sbaropeak   Yes, I  can see it now.   The GoogleMobileAdsMediationTestSuite requires an update to be compatible with iOS v9.x SDKs and we are working on an update. But also in the meantime we recommend using [Ad Inspector](https://developers.google.com/admob/ios/ad-inspector)
Sorry for the inconvenience.

**Comment by sbaropeak** [comment]
HI @chlandacastro ! No worries.

We are using Ad Inspector now, but we have some issues with it. Sometimes it displays just a blank screen or it displays an error on test devices registered on the AdMob UI (https://support.google.com/admob/answer/9691433).

Do you know when the update for GoogleMobileAdsMediationTestSuite would be released?

Thank you!

**Comment by ericleich** [comment]
This is now fixed when using Mediation Test Suite version 3.0.0 which adds support for Google Mobile Ads SDK iOS v9.x (see [release notes](https://developers.google.com/admob/ios/mediation-test-suite#3.0.0))
