### ISSUE TITLE
Project does not compile with newer Xcode versions

### ISSUE THREAD

**Issue by daniel-barros** [googleads/googleads-mobile-ios-mediation#358]
Adapter projects fail to build the framework target on Xcode 13.3.1, although they work fine with Xcode 13.0.
Here are the logs:
[Build Framework_2022-05-05T11-54-12.txt](https://github.com/googleads/googleads-mobile-ios-mediation/files/8630431/Build.Framework_2022-05-05T11-54-12.txt)

**Comment by joshuajplagonera** [comment]
Hi @daniel-barros , 
We have submitted a fix to use the new build system that resolves this issue. Let us know if you are still experiencing issues building.
