### ISSUE TITLE
Facebook mediation with FBAudienceNetwork 6.10 crashes

### ISSUE THREAD

**Issue by HsynKcmn** [googleads/googleads-mobile-ios-mediation#359]
I submit a build to Apple that includes GoogleMobileAdsMediationFacebook. Apple emailed to notify of this problem:

TMS-90863: Apple silicon Macs support issue - The app links with libraries that are not present on Mac:
@rpath/libfbobjc_ios-sdk_ads_src_FBAudienceNetwork_FBAudienceNetworkRelease.dylib

App works fine when deployed via Xcode; it only fails when I deploy to TestFlight!

Also my two app passed from app review with the problem. My users cant open my apps now !

**Comment by ericleich** [comment]
The `FBAudienceNetwork` binary is the Facebook Audience Network SDK. Per 
 https://developers.facebook.com/community/threads/453074943290160/, this looks like a Facebook SDK issue.
