### ISSUE TITLE
GoogleMobileAdsMediationIronSource Adapter Not ready 

### ISSUE THREAD

**Issue by AnyMindG** [googleads/googleads-mobile-ios-mediation#384]
Hi Team

After calling GADMobileAds startWithCompletionHandler, I get the following status:

 GADMobileAds *ads = [GADMobileAds sharedInstance];
          [ads startWithCompletionHandler:^(GADInitializationStatus *status) {
            // Optional: Log each adapter's initialization latency.
            NSDictionary *adapterStatuses = [status adapterStatusesByClassName];
            for (NSString *adapter in adapterStatuses) {
              GADAdapterStatus *adapterStatus = adapterStatuses[adapter];
              NSLog(@"Adapter Name:======== %@, Description:======== %@, Latency:======== %f", adapter,
                    adapterStatus.description, adapterStatus.latency);
            }
            // Start loading ads here...
          }];

GoogleMobileAdsMediationIronSource is Not Ready;No such adapter in the application.

**Error** 

Name: GADMediationAdapterIronSource, Description: <GADAdapterStatus: 0x600001e44800; state = Not Ready;No such adapter in the application.>, Latency: 0.000000

I have installed the GoogleMobileAdsMediationIronSource through the pod file.

Installing Google-Mobile-Ads-SDK (9.13.0) / Google-Mobile-Ads-SDK (9.11.0) **try with both version but not working** 
Installing GoogleMobileAdsMediationIronSource (7.2.5.1.0)
Installing IronSourceSDK (7.2.5.1)

**Comment by chlandacastro** [comment]
HI @AnyMindG!  Are you still having the same error.   I have tested our  test app and I can't duplicate that error.
