### ISSUE TITLE
Some files are missing in Example project 

### ISSUE THREAD

**Issue by AnyMindG** [googleads/googleads-mobile-ios-mediation#386]
Hi Team, I have downloaded the project but some files are missing for Objective C and Swift.

https://github.com/googleads/googleads-mobile-ios-mediation

Files Names

Objective C:

SampleCustomEventUtils.h
SampleCustomEventUtils.m

Swift:

SampleCustomEventUtilsSwift.swift

**Comment by joshh-devrel** [comment]
Closed as we have fixed the [build issue](https://github.com/googleads/googleads-mobile-ios-mediation/commit/f647fb76220256723e4c7fc77e05535aa70838c8) in the mediation example. Feel free to re-open this GitHub issue if the issue still persists.
