### ISSUE TITLE
error build: 6 duplicate symbols for architecture x86_64

### ISSUE THREAD

**Issue by mohdimran-3pg** [googleads/googleads-mobile-ios-mediation#398]
Hi Team,

I facing`error build: 6 duplicate symbols for architecture x86_64` error while building the`MediationExample` code. I am using Xcode `Version 14.0`
Can anyone please let me know if facing same issue?

<img width="1741" alt="Screenshot 2023-02-16 at 7 42 59 PM" src="https://user-images.githubusercontent.com/50764249/219388396-2d7a3872-65c7-4ed3-8c30-9b05e708be86.png">

**Comment by chlandacastro** [comment]
HI , @mohdimran-3pg  Chartboost iOS Adapter v9.2.0.0 was just released.   Could you verify if that solve this issue.  
https://developers.google.com/admob/ios/mediation/chartboost#chartboost-ios-mediation-adapter-changelog.

**Comment by joshh-devrel** [comment]
Closed as the build issue was fixed in [this commit](https://github.com/googleads/googleads-mobile-ios-mediation/commit/f647fb76220256723e4c7fc77e05535aa70838c8).
