### ISSUE TITLE
Cannot find adapter Mintegral

### ISSUE THREAD

**Issue by Z1yu** [googleads/googleads-mobile-ios-mediation#401]
init admob sdk success and GADMediationAdapterMintegral state is Ready （Admob 9.14 & GADMAdapterMintegralVersion 7.3.0）
but when load ads get this error:
Cannot find an ad network adapter with the name(s): Mintegral

**Comment by joshuajplagonera** [comment]
Hi @Z1yu 
Can you confirm if you can replicate the issue using [our sample apps](https://github.com/googleads/googleads-mobile-ios-examples) and the latest Mintegral adapter?

**Comment by Z1yu** [comment]
> Hi @Z1yu Can you confirm if you can replicate the issue using [our sample apps](https://github.com/googleads/googleads-mobile-ios-examples) and the latest Mintegral adapter?

I found the reason why it would appear when I used the AD Inspector and selected a single AD source test (Mintegral)
