### ISSUE TITLE
DTExchange Adapter: GoogleMobileAdsMediationFyber.h header isn't visible OOB

### ISSUE THREAD

**Issue by 2energycell** [googleads/googleads-mobile-ios-mediation#410]
Workaround: navigating manually into headers folder and dragging this header into application tree.
Expected result: after pods install, no manual actions should not be done.
Affected version: 8.2.0.0+.
@joshh-devrel

**Comment by 2energycell** [comment]
what should be imported is: #import <DTExchangeAdapter/DTExchangeAdapter.h>
but it's not clear where to find this;

**Comment by 2energycell** [comment]
@joshh-devrel can it be added to documentation?

**Comment by joshh-devrel** [comment]
@2energycell The issue wasn't reproducible on our end, feel free to re-open this GitHub issue if it still persists.
