### ISSUE TITLE
GADVideoController's isMuted cannot be referenced in nend ads

### ISSUE THREAD

**Issue by fan-n-kunimoto** [googleads/googleads-mobile-ios-mediation#412]
Referencing [isMuted](https://developers.google.com/admob/ios/api/reference/Classes/GADVideoController#ismuted), added in 10.2.0 of Mobile Ads SDK (iOS), causes EXC_BAD_ACCESS and crashes.
This event occurs when nend ads are displayed via AdMob mediation.

The following is the code that causes this event.
It is implemented to reference isMuted in the delegate method of the native video.
After debugging, it seems that isMuted does not exist in the videoController.

```
    func videoControllerDidPlayVideo(_ videoController: GADVideoController) {
        labelVideoController.text = putting(message: #function, adUnitId: adUnitId)
        print("isMuted =  \(String(describing: videoController.isMuted))")
    }
```
When displaying 3rd party ads such as nend via AdMob mediation,
Is isMuted of GADVideoController not usable?

### Environment
- Xcode 14.3
- iOS 15.7.3 (19H307）
- iPhone 6sPlus（Device）
- Google-Mobile-Ads-SDK (10.4.0)
- NendSDK_iOS (8.0.1)
- nend iOS Mediation Adapter（8.0.1.0）

**Comment by joshh-devrel** [comment]
Since `isMuted` is provided by the Google Mobile Ads SDK, this doesn't look like an issue caused by the mediation adapter. If the issue still persists, you can [contact](https://developers.google.com/admob/ios/support) Mobile Ads SDK support.
