### ISSUE TITLE
Swift Package Manager support

### ISSUE THREAD

**Issue by saldous** [googleads/googleads-mobile-ios-mediation#413]
Please, when will you do this? This is the only thing stopping me removing Cocoapods from my project because of your mediation adapters

This issue was logged almost 4 yrs ago here: https://github.com/googleads/googleads-mobile-ios-mediation/issues/172

We need GoogleMobileAdsMediationFacebook and GoogleMobileAdsMediationAppLovin and others to support Swift Package Manager.

The issue is example: I have Firebase installed with SPM, but have to use Cocoapods for GoogleMobileAdsMediationAppLovin, GoogleMobileAdsMediationFacebook. Then you end up with duplicate libraries and errors in xcode like: 
`Class GULHeartbeatDateStorage is implemented in both.  One of the two will be used. Which one is undefined.` because both pull down GoogleUtilities into different folders.

**Comment by stsandro** [comment]
I have a workaround for you. 
- download the zip file from the adapter you need
- extract it and re-zip the `.xcframework`
- compute the checksum `swift package compute-checksum /path/to/some.xcframework.zip`
- upload the somewhere where you can access it, e.g. S3
- create a swift package project that you can use in your actual project and to wrap it all up

Here is an example of what the `Package.swift` might look like:
```swift
// swift-tools-version:5.7
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "my-ad-adapters",
    platforms: [.iOS(.v15)],
    products: [
        .library(name: "AppLovinAds", targets: ["AppLovinAds"]),
    ],
    dependencies: [
        .package(url: "https://github.com/AppLovin/AppLovin-MAX-Swift-Package.git", exact: "11.8.2"),
    ],
    targets: [
        .target(
            name: "AppLovinAds",
            dependencies: [
                .product(name: "AppLovinSDK", package: "AppLovin-MAX-Swift-Package"),
                .target(name: "AppLovinAdapter"),
            ]
        ),
        .binaryTarget(
            name: "AppLovinAdapter",
            url: "https://your-s3-bucket.amazonaws.com/AppLovinAdapter-11.8.2/AppLovinAdapter.xcframework.zip",
            checksum: "abc123"
        ),
    ]
)
```

I'm doing this myself and have multiple library products in my Package.swift file, one library per ad network. I can now add the package to my app projects and import the libraries (ad networks) that I need/want in this app. If you need more details on setting this up, just ping me here.

**Comment by joshh-devrel** [comment]
Thanks for raising this GitHub issue. We have been looking into SPM support internally, but the ETA is still TBD. The [mediation dev doc](https://developers.google.com/admob/ios/choose-networks) will be updated once it becomes available.

**Comment by juanillo62gm** [comment]
What about this?
