### ISSUE TITLE
GoogleMobileAdsMediationFacebook changes project's target excluded architectures

### ISSUE THREAD

**Issue by saldous** [googleads/googleads-mobile-ios-mediation#432]
Through a process of trial and error creating a new project and slowly adding the pods I use until I hit the issue, I was able to identify that GoogleMobileAdsMediationFacebook 6.14.0.0 changes the xcode excluded architectures of the target.

Before installing this pod:
<img width="898" alt="image" src="https://github.com/googleads/googleads-mobile-ios-mediation/assets/3334306/95fdb7e8-bb18-4531-a333-009be55b27aa">

After installing it:
<img width="942" alt="image" src="https://github.com/googleads/googleads-mobile-ios-mediation/assets/3334306/4667aa2c-da8f-453b-a47d-a35791aac240">

This results in not being able to run the project on the iOS simulator, because arm64 is excluded...
<img width="632" alt="image" src="https://github.com/googleads/googleads-mobile-ios-mediation/assets/3334306/fac2c3ec-b3e8-40c5-bc06-17cf7fc5510b">

This Podfile works:
```
platform :ios, '14.0'

target 'PodsTesting' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Google-Mobile-Ads-SDK'

post_install do |installer|
    installer.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
        config.build_settings['IOS_DEPLOYMENT_TARGET'] = '14.0'
      end
    end
  end

end
```

This Podfile causes the issue:
```
platform :ios, '14.0'

target 'PodsTesting' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Google-Mobile-Ads-SDK'
pod 'GoogleMobileAdsMediationFacebook'

post_install do |installer|
    installer.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
        config.build_settings['IOS_DEPLOYMENT_TARGET'] = '14.0'
      end
    end
  end

end
```

Removing GoogleMobileAdsMediationFacebook pod results in the excluded architectures returning to normal. Re-adding it creates the problem again.

Please fix this!!
(using xcode 14.3.1, cocoapods 1.12.1 on an M1 Max Mac)

**Comment by NVentimiglia** [comment]
Confirming i386 support was removed by Meta.

https://github.com/CocoaPods/Specs/blob/master/Specs/2/1/5/FBAudienceNetwork/6.14.0/FBAudienceNetwork.podspec.json#L49

**Comment by saldous** [comment]
@NVentimiglia you miss-understood. They added the exclude of arm64. So now you can't build it on either an Intel OR a Apple Silicon mac... this surely must be a mistake? How else are we supposed to test this?

**Comment by joshh-devrel** [comment]
@saldous 
Thanks for reporting the issue.
We are currently looking into this with Meta team and will provide an update here.

**Comment by saldous** [comment]
@joshh-devrel  any update?

**Comment by joshh-devrel** [comment]
@saldous 

Meta team has fixed the issue: the exclusion of arm64 (simulator architecture) has been removed in the [podspec](https://github.com/CocoaPods/Specs/blob/master/Specs/2/1/5/FBAudienceNetwork/6.14.0/FBAudienceNetwork.podspec.json) file for Audience Network v6.14.0.

**Comment by saldous** [comment]
> @saldous
> 
> Meta team has fixed the issue: the exclusion of arm64 (simulator architecture) has been removed in the [podspec](https://github.com/CocoaPods/Specs/blob/master/Specs/2/1/5/FBAudienceNetwork/6.14.0/FBAudienceNetwork.podspec.json) file for Audience Network v6.14.0.

I just did a pod repo update, pod install. Same issue is still present. Not sure why it's not picking up the change?

**Comment by saldous** [comment]
@joshh-devrel any update? It still doesn't work..

**Comment by masarusanjp** [comment]
@saldous 

I had the same problem, but it was resolved.
Maybe deleting the local repo and then running pod install will solve it.

```shell

$ pod repo remove trunk
$ pod install --repo-update

```

**Comment by saldous** [comment]
@masarusanjp thank you! That worked
