### ISSUE TITLE
Using "@import" in Vungle adaptor 5.3.2 doesn't compile if project is using Object-C++

### ISSUE THREAD

**Issue by kkwezard** [googleads/googleads-mobile-ios-mediation#44]
The latest Vungle adapter replace the "#import" syntax with "@import" to import framework/module.
But this will break projects that include ".mm" files which actually use object-C++ that doesn't support "modules" in iOS.

**Comment by maninomula** [comment]
Thanks for bringing in the question. The latest version of Vungle Adapter 6.2.0.2 solves this issue.
