### ISSUE TITLE
Problems with the versions in the Info.plist files

### ISSUE THREAD

**Issue by stsandro** [googleads/googleads-mobile-ios-mediation#448]
There are some restrictions around what a proper version looks like. I get the following error when building my app for release on Xcode Cloud:
> ITMS-90060: This bundle is invalid - The value for key CFBundleShortVersionString '12.2.1.0' in the Info.plist file at 'Payload/MyCool.app/Frameworks/AppLovinAdapter.framework' must be a period-separated list of at most three non-negative integers. Please find more information about CFBundleShortVersionString at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleshortversionstring

There is also another problem regarding the minimum supported version:
>ITMS-90208: Invalid Bundle - The bundle MyCool.app/Frameworks/AppLovinAdapter.framework does not support the minimum OS Version specified in the Info.plist.

This error is also emitted from other frameworks like [GoogleMobileAds](https://github.com/googleads/swift-package-manager-google-mobile-ads)

As far as I can tell this problem only occurs with **Xcode 15.3**

**Comment by Palbrevik** [comment]
Similar issue, but within MetaAdapter.frameWork:  "key CFBundleShortVersionString '6.15.0.0' in the Info.plist file at 'Payload/Tradera.app/Frameworks/MetaAdapter.framework' must be a period-separated list of at most three non-negative integers. Please find more information about CFBundleShortVersionString at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleshortversionstring". 

This problem occurs in Xcode 15.3 and Xcode 15.4, but not on Xcode 15.0.

**Comment by SzGajdzica** [comment]
Now GoogleMobileAds requires xcode 15.3 and this dependency blocks it. Please post a fix on that!

**Comment by rursache** [comment]
you can edit the `info.plist` inside the framework file and change the `CFBundleShortVersionString` to `6.15.0` until google get their 💩 together. same for the other mediators if needed

**Comment by s2mr** [comment]
The workaround above does not seem to work with Xcode15.4.
In Xcode15.4, the Code sign check fails if there are changes to files in the framework.

```
/projects/Pods/MyFramework.xcframework:1:1: error: The signature of MyFramework.xcframework” cannot be verified.
    note: A sealed resource is missing or invalid
    note: /projects/Pods/MyFramework.xcframework: a sealed resource is missing or invalid
file modified: /projects/Pods/MyFramework.xcframework/ios-arm64_x86_64-simulator/MyFramework.framework/Info.plist
file modified: /projects/Pods/MyFramework.xcframework/ios-arm64/MyFramework.framework/Info.plist
```

Hopefully Google will respond soon!

**Comment by awilliams88** [comment]
I see a strange versioning issue in the `FBAudienceNetwork 6.15.1` which is hosted by META at this [link](https://developers.facebook.com/resources/FBAudienceNetwork-6.15.1.zip).

When I open the `Info.plist` file inside the `FBAudience.xcframework`, I still see version as `6.15.0`.

I am not 100% sure but probably as per [this POST](https://github.com/googleads/googleads-mobile-ios-mediation/issues/167) version conflict is causing an issue with the latest released Meta Adaptor [Version 6.15.1.0](https://dl.google.com/googleadmobadssdk/mediation/ios/meta/MetaAdapter-6.15.1.0.zip)

This is causing the following error when I try to start the google admob sdk with Meta Mediation enabled.

```
["GADMediationAdapterFacebook": <GADAdapterStatus: 0x600001808bc0; state = Not Ready;No such adapter in the application.>, "GADMobileAds": <GADAdapterStatus: 0x600001808c40; state = Ready>]
```

Probably not directly related to this issue, but versioning is causing issues with adapters for mediation networks.

**Comment by SzGajdzica** [comment]
Still nothing, I think we can comment here and wait for several years and nothing will change...

**Comment by malandr2** [comment]
Hello @all, 

If you're having a mediation issues please create a new thread in the [AdMob developers forum](https://groups.google.com/g/google-admob-ads-sdk) for us to begin the troubleshooting process. Closing this out as triaging will take place in the forum  - Thanks!

**Comment by cjwirth** [comment]
@malandr2 Thanks for pointing us in what is supposed to be the right channel, but I mean, it seems like the forums over there are quite flooded and there have been multiple threads with similar complaints that haven't actually been resolved. So I'm not sure if going over there is a way to solve anything, or just a way to make it easier to ignore us?

- [Status Update on SwiftPM support for mediation libraries](https://groups.google.com/g/google-admob-ads-sdk/c/To0CORrnC-s/m/V0D09AwvAAAJ)
  - Opened in June 2024, not a single response, even though its simply asking for an update
- [Swift Package Manager - Mediation adapter libraries](https://groups.google.com/g/google-admob-ads-sdk/c/5rl04DtDei8/m/cSH3utkXBAAJ)
  - Feb 2023, response saying there's no timeline to support SwiftPM
- [Swift Package Manager Support](https://groups.google.com/g/google-admob-ads-sdk/c/w3CNzdaJFDs/m/WJ2Zes0eBAAJ)
  - October 2020; Last response January 2022 saying it's under discussion
- [GADMAdapterGoogleAdMobAds not Ready - Meta integration](https://groups.google.com/g/google-admob-ads-sdk/c/O3pdeYju42Y/m/e4tixVfhAwAJ)
  - Last response September 2022 - mediation via SwiftPM isn't supported yet
