### ISSUE TITLE
Crash in [NSCache setObject:forKey:cost:] - attempt to insert nil value

### ISSUE THREAD

**Issue by Neral** [googleads/googleads-mobile-ios-mediation#50]
We noticed an increase in crashes while trying to load an ad.

It seems the issue is here: [InMobiMediatedNativeAppInstallAd.m#L86](https://github.com/googleads/googleads-mobile-ios-mediation/blob/master/adapters/InMobi/InMobiAdapter/InMobiMediatedNativeAppInstallAd.m#L86)
If `NSData` fails to load an image it still going to set a nil object.

The issue introduced with commit https://github.com/googleads/googleads-mobile-ios-mediation/commit/1a952d127f9a23bbc00c691e25cf5722195d746c as the previous implementation has check for nil object https://github.com/googleads/googleads-mobile-ios-mediation/commit/1a952d127f9a23bbc00c691e25cf5722195d746c?diff=split#diff-0144ea4814b9001d3fffcd88ee007f84L112

### Crash
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSCache setObject:forKey:cost:]: attempt to insert nil value

### Debug log
```
Fatal Exception: NSInvalidArgumentException
-[InMobiMediatedNativeAppInstallAd initWithInMobiNativeAppInstallAd:withAdapter:
shouldDownloadImage:withCache:]_block_invoke
```

**Comment by maninomula** [comment]
The PR has been merged and a new version of the adapter is release with the changes.
