### ISSUE TITLE
Incorrect delegate method implementation of Facebook 4.28.0

### ISSUE THREAD

**Issue by llmagicll** [googleads/googleads-mobile-ios-mediation#62]
FAN cannot receive OnAdRewarded event due to the adapter issue.
The facebook rewarded video delegate is:

(void)rewardedVideoAdVideoComplete:(FBRewardedVideoAd *)rewardedVideoAd;

However in Facebook adapter is implemented as (4.28.0):

(void)rewardedVideoAdComplete:(FBRewardedVideoAd *)rewardedVideoAd
That is a big mistake

**Comment by rampara** [comment]
This issue has been resolved.
