### ISSUE TITLE
Not compatible with mopub 5.0

### ISSUE THREAD

**Issue by bitomule** [googleads/googleads-mobile-ios-mediation#77]
Mopub has updated their sdk to version 5.0.0 with GDPR support included. 

We want to update in order to support that new GDPR features but google ads mopub mediation adapter still requires an old version. 

Is an update on this planned? Any other way to support mopub GDPR without the adapter?

**Comment by maninomula** [comment]
We are planning to release the latest version of the MoPubAdapter by today. So please stay tuned.

**Comment by maninomula** [comment]
A new version of MoPubAdapter(5.0.0.0) is released and available in Cocoapods.
