### ISSUE TITLE
Facebook Audience Network 4.99.2

### ISSUE THREAD

**Issue by huyduc** [googleads/googleads-mobile-ios-mediation#81]
Facebook released another version of their SDK that fixed a few important crash. Could we update the mediation to this version too? 
https://developers.facebook.com/docs/audience-network/changelog-ios#4_99_2
```
Fixed a crash when trying to cache multiple images
Fixed a crash during network connection initialization
Fixed the collection view sample in AdUnitsSample project
```

**Comment by maninomula** [comment]
@huyduc We are already working on that and will release a new version soon.
Thanks.

**Comment by maninomula** [comment]
@huyduc Facebook Adapter version 4.99.2.0 is live now.
