### ISSUE TITLE
Facebook Audience Network 5.0.1

### ISSUE THREAD

**Issue by ilozano** [googleads/googleads-mobile-ios-mediation#85]
Facebook released another version of their SDK fixing a critical bug that freezes the UI. Could we update the mediation to this version too?

https://developers.facebook.com/docs/audience-network/changelog-ios#5_0_1

Thanks!

**Comment by maninomula** [comment]
Hi @ilozano ,
We are working on releasing the FacebookAdapter version 5.0.1.0. The adapter will be out soon. 
Thanks

**Comment by maninomula** [comment]
Closing this issue as the Facebook Adapter version 5.0.1.0 is out.
