### ISSUE TITLE
Could not build module

### ISSUE THREAD

**Issue by volythat** [googleads/googleads-mobile-ios-mediation#9]
Hi 

I can't integrate Chartboost adapter into my project (swift 3). I used `pod 'GoogleMobileAdsMediationChartboost'` and set `Allow Non-modular Includes In Framework Modules` to YES . 
But i can't import framework, it says "Could not build module 'ChartboostAdapter'"

i tried : clean , reboot, integrate manual

Please help me !

**Comment by ericleich** [comment]
Are you using `use_frameworks!`?

https://blog.cocoapods.org/CocoaPods-0.36/ has some background. 

https://github.com/googleads/googleads-mobile-ios-examples/blob/master/Swift/admob/BannerExample/Podfile#L6 shows an example Swift Podfile.

**Comment by volythat** [comment]
i already use `use_frameworks!`

**Comment by volythat** [comment]
My project : https://drive.google.com/file/d/0B1Ju4D2yzMElWm5PQ3N6TzlkTmc/view?usp=sharing

**Comment by ericleich** [comment]
A new version of the Chartboost adapter (6.6.3.0) was pushed out today that addresses this issue. The Chartboost SDK is not modular, and when the adapter tried to import it from a public header, it was causing issues in Swift. The adapter now no longer imports the SDK.

Your project should just work now if you update the pods. If you do want to use the Chartboost ad network extras, you'll need to import both the Chartboost adapter and Chartboost SDK from your app. For the Chartboost SDK in particular, this would require using the bridging header.

**Comment by volythat** [comment]
i just update pod, it work
Thank you very much ! 👍

**Comment by ericleich** [comment]
Awesome, glad this worked for you!
